import type {Metadata} from "next";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import NavBar from "@/components/layout/NavBar";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning
              className={cn("font-sans", inter.variable)}>
        <body>
        <ThemeProvider attribute="class"
                       defaultTheme="system"
                       enableSystem>
            <div className="bg-surface">
                <div className="min-h-screen max-w-7xl mx-auto flex flex-col text-primary">
                    <nav className="bg-surface-low xl:rounded-b-2xl">
                        <NavBar/>
                    </nav>


                    <main className="px-4 xl:px-0">
                        {children}
                    </main>
                </div>
            </div>
        </ThemeProvider>
        </body>
        </html>
    );
}
